#source 'https://medxcom:85a04942865283e25c5de4fbdea26c8c@gems.medx.com/6d2204db67be9f89812f9be8889cb0da/'
source 'http://rubygems.org'
ruby '1.9.3'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'aws-sdk', '< 2.0.0'
gem 'shoryuken'
gem 'mysql2', '~> 0.3.10'
gem 'authlogic'
gem 'kaminari'
gem 'inifile'
gem 'paperclip', '~> 4.0'
gem 'apn_sender', :require => 'apn'
gem 'daemons'
gem 'json'
gem 'geocoder'
gem 'fastercsv'
gem 'airbrake'
gem 'savon', '~> 1.2.0'
gem 'ckeditor'
gem 'rake'
gem 'chargify_api_ares', '~> 1.0.5'
gem 'ruby-audioinfo', '~> 0.5.1'
gem 'best_in_place'
gem 'haml'
gem 'typhoeus'
gem 'combined_time_select', '~> 1.0.1'
gem 'dynamic_form'
gem 'watu_table_builder', :require => 'table_builder'
gem 'httparty'
gem 'aws-sessionstore-dynamodb'

#Javascripts
gem 'jquery-rails'
gem 'jquery-migrate-rails'
gem 'jquery-validation-rails'
gem 'jquery-timepicker-rails'
gem 'rails3-jquery-autocomplete'
gem 'flot-rails', :git => 'https://github.com/Kjarrigan/flot-rails.git'
gem 'jquery-colorbox-rails', '0.1.4'

#Sytlesheets
gem 'jquery-ui-sass-rails'

# in production environments by default.
gem 'sass-rails', ' ~> 3.1.0'

#Integration with Mi7.io
gem 'license-to-kill', git: 'https://7548f35ef688426e55c1d242a302da269ca3fc13:x-oauth-basic@github.com/MedXCom/license-to-kill.git'
gem 'unify-health', git: 'https://7548f35ef688426e55c1d242a302da269ca3fc13:x-oauth-basic@github.com/MedXCom/unify-health.git'

# Gems used only for assets and not required
group :assets do
  gem 'execjs'
  gem 'therubyracer'
  gem 'uglifier'
end

group :development do
  gem 'hirb'
  gem 'awesome_print'
  gem 'spring'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'capybara-email'
  gem 'capybara-screenshot'
  gem 'selenium-webdriver'
  gem 'factory_girl_rails', require: false
  gem 'database_cleaner'
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-stack_explorer'
end

group :test do
  gem 'ci_reporter_rspec'
  gem 'timecop'
end
